platform:ios, 8.0

use_frameworks!
inhibit_all_warnings!
target 'CollectionViewWheelLayoutSwift_Example' do
    pod 'CPCollectionViewKit', :path => '../..'
    pod 'Reveal-iOS-SDK', :configurations => ['Debug']
  target 'CollectionViewWheelLayoutSwift_Tests' do
    inherit! :search_paths
  end
end
